name: "Build java service"
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'

concurrency:
  group: argocd-for-dev-build
  cancel-in-progress: true

jobs:
  build:
    name: build maven project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'
      - name: maven build
        run: mvn -B package --file pom.xml
      - name: tag
        id: tag
        run: |
          echo ::set-output name=git_rev::$(git rev-parse --short HEAD)
          echo "${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then
            TAG="${{ github.ref_name }}"
            echo "TAG: ${{ github.ref_name }}"
            echo ::set-output name=image_tags::${TAG:1} $(git rev-parse --short HEAD)
          else
            echo ::set-output name=image_tags::$(git rev-parse --short HEAD) $(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          fi
      - name: docker image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: argocd-for-dev
          tags: ${{ steps.tag.outputs.image_tags }}
          dockerfiles: ./Dockerfile

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: quay.io/java_shevtsov

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/java_shevtsov
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
