name: release service

on:
  push:
    branches:
      - main

env:
  git-user: 'ivan-shevtsov'
  git-email: 'java.shevtsov@gmail.com'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: minor
          tag_prefix: "v"

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
